### ISSUE TITLE
Idea: setup a basic GUI for eascase 

### ISSUE THREAD

**Issue by DanielcoderX** [uoosef/bepass#11]

**Comment by uoosef** [comment]
Yes, im currently working on a minimal cross platform gui for windows, linux and mac based on this library
https://github.com/fyne-io/fyne
Also for android im working on a minimal demo tun2socks project based on trojan-gfw-go but a fully operational and usable android version will be plugin for hiddify and nekobox that its also in planning stage...

there isn't any active planning for ios because im not familiar (and unwilling to learn) ios development so a maintainer for future ios version is verymuch needed

**Comment by DanielcoderX** [comment]
Flawless :) yesterday I was thinking to that and tried something about minimal GUI exactly using **fyne** but i noticed something that I was confused 🤔 about how using the core, as a single external binary dependecy and bind it or use to call the core as a library and bind it...

Hmm, Android.... let's me just try a little a changes and bind it using _gomobile_, wish it won't bother a lot😁

_Someone_ made a version using Python/TK, if you are interested in testing it you can dm me on telegram to give you the binary and the creator channel
